"""phantom-client — generic async Python SDK for the Phantom upload proxy.

The single import you need: ``from phantom_client import PhantomClient``.
Every other public name (model classes, config classes, exception
hierarchy, header constants) is also re-exported from this package
root for convenience.

See ``docs/architecture-intent.md`` §4.2 for the full surface.
"""

from __future__ import annotations

from phantom_client.client import PhantomClient
from phantom_client.config import ClientConfig, RetryPolicy, SubmitOptions, Timeouts
from phantom_client.errors import (
    EXCEPTION_FOR_CODE,
    EmptyFilterError,
    PhantomBadRequestError,
    PhantomClientError,
    PhantomConflictError,
    PhantomConnectError,
    PhantomEnvelopeError,
    PhantomHttpError,
    PhantomNetworkError,
    PhantomNotFoundError,
    PhantomPayloadTooLargeError,
    PhantomRateLimitedError,
    PhantomServerError,
    PhantomTimeoutError,
    PhantomTransportError,
    PhantomUnauthorizedError,
    PhantomUnavailableError,
    PhantomUnprocessableError,
    PhantomValidationError,
    PollDeadlineExceeded,
)
from phantom_client.headers import (
    X_PHANTOM_ATTEMPTS,
    X_PHANTOM_GROUP_ID,
    X_PHANTOM_IDEMPOTENCY_KEY,
    X_PHANTOM_INSTANCE,
    X_PHANTOM_MULTIFILE_ID,
    X_PHANTOM_NEXT_ATTEMPT_AT,
    X_PHANTOM_ORDER,
    X_PHANTOM_STATUS,
    X_PHANTOM_SUGGESTED_POLL_AFTER,
    X_PHANTOM_UID,
    X_PHANTOM_UPLOAD_ID,
    build_request_headers,
)
from phantom_client.models import (
    TERMINAL_STATES,
    AdminStatusResponse,
    BulkDeleteResponse,
    CapturedStep,
    ChainAdminDetail,
    ChainAdminStepDetail,
    ChainBody,
    ChainBodyBytes,
    ChainBodyJson,
    ChainBodyRef,
    ChainBodyText,
    ChainCapture,
    ChainEnvelope,
    ChainResponse,
    ChainState,
    ChainStep,
    DeleteFilter,
    ExtractFilter,
    GroupMember,
    GroupStatusResponse,
    HealthResponse,
    IdentifierLookupResponse,
    InstanceStatusResponse,
    InstanceSummary,
    KeyValueMatchFilter,
    ListUploadsResponse,
    ReadyResponse,
    ResponseHeaders,
    SortKey,
    StatsResponse,
    TokenSlot,
    UploadBundle,
    UploadRow,
    UploadState,
    UploadStatusSummary,
    parse_response_headers,
)
from phantom_client.poller import poll_group_until_finished, poll_until

__version__ = "0.1.0"

__all__ = [
    "EXCEPTION_FOR_CODE",
    "TERMINAL_STATES",
    "X_PHANTOM_ATTEMPTS",
    "X_PHANTOM_GROUP_ID",
    "X_PHANTOM_IDEMPOTENCY_KEY",
    "X_PHANTOM_INSTANCE",
    "X_PHANTOM_MULTIFILE_ID",
    "X_PHANTOM_NEXT_ATTEMPT_AT",
    "X_PHANTOM_ORDER",
    "X_PHANTOM_STATUS",
    "X_PHANTOM_SUGGESTED_POLL_AFTER",
    "X_PHANTOM_UID",
    "X_PHANTOM_UPLOAD_ID",
    "AdminStatusResponse",
    "BulkDeleteResponse",
    "CapturedStep",
    "ChainAdminDetail",
    "ChainAdminStepDetail",
    "ChainBody",
    "ChainBodyBytes",
    "ChainBodyJson",
    "ChainBodyRef",
    "ChainBodyText",
    "ChainCapture",
    "ChainEnvelope",
    "ChainResponse",
    "ChainState",
    "ChainStep",
    "ClientConfig",
    "DeleteFilter",
    "EmptyFilterError",
    "ExtractFilter",
    "GroupMember",
    "GroupStatusResponse",
    "HealthResponse",
    "IdentifierLookupResponse",
    "InstanceStatusResponse",
    "InstanceSummary",
    "KeyValueMatchFilter",
    "ListUploadsResponse",
    "PhantomBadRequestError",
    "PhantomClient",
    "PhantomClientError",
    "PhantomConflictError",
    "PhantomConnectError",
    "PhantomEnvelopeError",
    "PhantomHttpError",
    "PhantomNetworkError",
    "PhantomNotFoundError",
    "PhantomPayloadTooLargeError",
    "PhantomRateLimitedError",
    "PhantomServerError",
    "PhantomTimeoutError",
    "PhantomTransportError",
    "PhantomUnauthorizedError",
    "PhantomUnavailableError",
    "PhantomUnprocessableError",
    "PhantomValidationError",
    "PollDeadlineExceeded",
    "ReadyResponse",
    "ResponseHeaders",
    "RetryPolicy",
    "SortKey",
    "StatsResponse",
    "SubmitOptions",
    "Timeouts",
    "TokenSlot",
    "UploadBundle",
    "UploadRow",
    "UploadState",
    "UploadStatusSummary",
    "build_request_headers",
    "parse_response_headers",
    "poll_group_until_finished",
    "poll_until",
]
